#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    ait3content-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^ait3content\.ddev\.site$`)
      
      service: "ait3content-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "ait3content-redirectHttps"
    ait3content-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^ait3content\.ddev\.site$`)
      
      service: "ait3content-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "ait3content-redirectHttps"
    ait3content-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^ait3content\.ddev\.site$`)
      
      service: "ait3content-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "ait3content-redirectHttps"
    
    
    
    ait3content-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^ait3content\.ddev\.site$`)
      
      service: "ait3content-web-80"
      ruleSyntax: v3
      
      tls: true
      
    ait3content-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^ait3content\.ddev\.site$`)
      
      service: "ait3content-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    
    ait3content-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^ait3content\.ddev\.site$`)
      
      service: "ait3content-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    ait3content-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    ait3content-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-ait3content-web:80
        
    ait3content-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-ait3content-web:8025
        
    
    
    ait3content-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-ait3content-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/ait3content.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/ait3content.key